flags: {}
packages:
- './manifolds-core'
- './manifolds'
- './manifold-random'
extra-deps:
- number-show-0.1.0.0
- pragmatic-show-0.1.2.0
- constrained-categories-0.4.0.0
- free-vector-spaces-0.1.5.0
- linearmap-category-0.3.5.0
- vector-space-0.14
- spatial-rotations-0.1.0.1
- trivial-constraint-0.4.0.0
resolver: lts-14.0
